package test

import (
	"os"
	"path/filepath"
	"testing"
	"text/template"

	"github.com/stretchr/testify/require"
)

// RunCreateTestFileFromTemplate_DebugOutput verifies the diagnostic logging capabilities of
// the `createTestFileFromTemplate` test helper function. This function is essential for
// preparing `.http` request files from templates for various tests.
// The test executes `createTestFileFromTemplate` using
// 'test/data/http_request_files/system_var_datetime.http' as a template and observes the
// `t.Logf` output generated by the helper, ensuring it provides useful debugging information
// during test execution and setup.
func RunCreateTestFileFromTemplate_DebugOutput(t *testing.T) {
	t.Helper()
	templateFileName := "system_var_datetime.http"
	wd, err := os.Getwd()
	require.NoError(t, err, "Failed to get working directory")
	templatePath := filepath.Join(wd, "test/data", "http_request_files", templateFileName)

	// Check if the source template file exists
	_, err = os.Stat(templatePath)
	require.NoError(t, err, "Source template file %s does not exist", templatePath)

	t.Logf("Attempting to process template: %s", templatePath)

	data := struct{ ServerURL string }{ServerURL: "http://localhost:12345/mockserver"}

	// Call the function under test
	// The t.Logf calls inside createTestFileFromTemplate should execute here
	processedFilePath := createTestFileFromTemplate(t, templatePath, data)
	require.NotEmpty(t, processedFilePath, "createTestFileFromTemplate returned an empty path")

	// Clean up the created temporary file
	defer func() {
		errRemove := os.Remove(processedFilePath)
		if errRemove != nil {
			t.Logf("Warning: failed to remove temporary file %s: %v", processedFilePath, errRemove)
		}
	}()

	t.Logf("TestCreateTestFileFromTemplate_DebugOutput completed. Processed file was: %s", processedFilePath)
	// No specific assertions needed here, the goal is to observe t.Logf output from the helper.
}

// createTestFileFromTemplate processes a template file and returns the path to the processed file.
// Kept here for the TestCreateTestFileFromTemplate_DebugOutput wrapper only; no other caller
// remains after batch-2c.
func createTestFileFromTemplate(t *testing.T, templatePath string, data any) string {
	t.Helper()
	tmplContent, err := os.ReadFile(templatePath)
	require.NoError(t, err)

	t.Logf("[DEBUG_CREATE_TEST_FILE] Original template content for %s:\n%s", templatePath, string(tmplContent))

	// Use different delimiters to avoid conflict with {{...}} used by the library itself.
	tmpl, err := template.New("testfile").Delims("[[", "]]").Parse(string(tmplContent))
	require.NoError(t, err)

	tempFile, err := os.CreateTemp(t.TempDir(), "processed_*.http")
	require.NoError(t, err)
	tempFileName := tempFile.Name()

	require.NoError(t, tmpl.Execute(tempFile, data))
	require.NoError(t, tempFile.Close())

	// Read back the content of the temporary file to log what was actually written.
	writtenContent, readErr := os.ReadFile(tempFileName)
	require.NoError(t, readErr, "Failed to read back temp file for debugging: %s", tempFileName)
	t.Logf("[DEBUG_CREATE_TEST_FILE] Content written to temp file %s:\n%s", tempFileName, string(writtenContent))

	return tempFileName
}
