version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - bodyclose
    - misspell
    - staticcheck
    - unused
    - ineffassign
    - funlen
    - revive
    - dupl
  exclusions:
    rules:
      - path: '(.+)_test\.go$'
        linters:
          - errcheck
  settings:
    funlen:
      lines: 100
      statements: 60
    revive:
      rules:
      - name: var-naming
        disabled: true
      - name: file-length-limit
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - max: 1000
            skip-comments: true
            skip-blank-lines: true

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
