version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - bodyclose
    - misspell
    - staticcheck
    - unused
    - ineffassign
    - unparam
    - dupl
    - nestif
    - funlen
    - revive
    - testpackage
    - thelper
  exclusions:
    rules:
      - path: '(.+)_test\.go$'
        linters:
          - errcheck
  settings:
    funlen:
      lines: 100
      statements: 60
    revive:
      enable-all-rules: false
      rules:
      - name: add-constant
        disabled: true
      - name: var-naming
        disabled: true
      - name: line-length-limit
        disabled: true
        arguments: [120]
      - name: file-length-limit
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - max: 1000
            skip-comments: false
            skip-blank-lines: false
    nestif:
      min-complexity: 4

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
