version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - bodyclose
    - misspell
    - staticcheck
    - unused
    - ineffassign
    - unparam
    - dupl
    - nestif
    - revive
    - testpackage
    - thelper
  exclusions:
    rules:
      - path: '.*test.*\.go$'
        linters:
          - errcheck
          - unparam
  settings:
    revive:
      enable-all-rules: true
      rules:
      - name: package-comments
        disabled: true
      - name: add-constant
        disabled: true
        exclude: ["**/*_test.go", "test/*.go"]
        arguments:
          - max-lit-count: "3"
            allow-strs: '""'
            allow-ints: "0"
            allow-floats: "0.0"
      - name: var-naming
        disabled: true
      - name: line-length-limit
        arguments: [120]
      - name: function-length
        arguments: [100, 0]
      - name: file-length-limit
        arguments:
          - max: 1000
            skip-comments: false
            skip-blank-lines: false
      - name: unhandled-error
        exclude: ["**/*_test.go", "test/*.go"]
      - name: exported
        exclude: ["**/*_test.go", "test/*.go"]
        disabled: true
    nestif:
      min-complexity: 4

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
