name: Go Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Or your project's Go version

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run checks
      run: |
        make install-lint
        make check
