name: Go Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run lint
      run: |
        make install-lint
        make lint

    - name: Run tests
      run: |
        make install-gotestsum
        make test
